<?php
// employee/salary.php
require_once '../config/db.php';
require_once '../includes/emp_header.php';

$emp_id = $_SESSION['employee_db_id'];

$stmt = $pdo->prepare("SELECT * FROM salary_records WHERE employee_id = :eid ORDER BY year DESC, month DESC");
$stmt->execute(['eid' => $emp_id]);
$salaries = $stmt->fetchAll();
?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">My Salary History</h1>
</div>

<div class="alert alert-info">
    <i class="bi bi-info-circle me-2"></i> Salary reports are generated by Admin at the end of each month.
</div>

<div class="card border-0 shadow-sm">
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-custom mb-0">
                <thead>
                    <tr>
                        <th>Month/Year</th>
                        <th>Present Days</th>
                        <th>Absent Days</th>
                        <th>Total Salary</th>
                        <th>Date Generated</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($salaries) > 0): ?>
                        <?php foreach ($salaries as $row): ?>
                            <tr>
                                <td><?php echo date('F Y', mktime(0, 0, 0, $row['month'], 1, $row['year'])); ?></td>
                                <td><?php echo $row['present_days']; ?></td>
                                <td><?php echo $row['absent_days']; ?></td>
                                <td class="fw-bold text-success"><?php echo format_money($row['total_salary']); ?></td>
                                <td class="text-muted small"><?php echo date('M j, Y', strtotime($row['generated_at'])); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="5" class="text-center py-4">No salary records found.</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php require_once '../includes/emp_footer.php'; ?>